#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-10-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_auto_20191026_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='handling',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='container.ContainerHandling'),
        ),
    ]
