#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_auto_20191026_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerhandling',
            name='handling_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
