#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-10-26 08:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0009_auto_20191026_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now=True)),
                ('container_info', jsonfield.fields.JSONField(default=dict)),
                ('handling', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='container.ContainerHandling')),
            ],
        ),
    ]
