#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-10-26 09:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_containerlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerlog',
            name='container_info',
        ),
        migrations.AddField(
            model_name='containerlog',
            name='captured_images',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='containerlog',
            name='container_code',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
