#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-10-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0014_containerhandling_handling_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
