#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-10-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0015_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
