#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-11-30 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0017_containerlog_inout'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRWorker',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_area_min_size', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.IntegerField(choices=[(0, 'Stopped'), (1, 'Running'), (2, 'Error')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='singlehandlingworkerconfig',
            name='back_camera',
        ),
        migrations.RemoveField(
            model_name='singlehandlingworkerconfig',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='singlehandlingworkerconfig',
            name='handling',
        ),
        migrations.RemoveField(
            model_name='singlehandlingworkerconfig',
            name='left_camera',
        ),
        migrations.RemoveField(
            model_name='singlehandlingworkerconfig',
            name='right_camera',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='container_side',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='handling',
        ),
        migrations.RemoveField(
            model_name='containerlog',
            name='handling',
        ),
        migrations.AddField(
            model_name='camera',
            name='use_for_ocr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='containerlog',
            name='back_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_back_camera', to='container.Camera'),
        ),
        migrations.AddField(
            model_name='containerlog',
            name='front_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_front_camera', to='container.Camera'),
        ),
        migrations.AddField(
            model_name='containerlog',
            name='left_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_left_camera', to='container.Camera'),
        ),
        migrations.AddField(
            model_name='containerlog',
            name='right_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_right_camera', to='container.Camera'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Disconnected'), (0, 'Unknown'), (1, 'Ready'), (2, 'Running')], default=0),
        ),
        migrations.DeleteModel(
            name='ContainerHandling',
        ),
        migrations.DeleteModel(
            name='SingleHandlingWorkerConfig',
        ),
        migrations.AddField(
            model_name='ocrworker',
            name='back_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_worker_back_camera', to='container.Camera'),
        ),
        migrations.AddField(
            model_name='ocrworker',
            name='front_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_worker_front_camera', to='container.Camera'),
        ),
        migrations.AddField(
            model_name='ocrworker',
            name='left_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_worker_left_camera', to='container.Camera'),
        ),
        migrations.AddField(
            model_name='ocrworker',
            name='right_camera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_worker_right_camera', to='container.Camera'),
        ),
    ]
