#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0018_auto_20191130_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Disconnected'), (1, 'Ready'), (2, 'Running')], default=-1),
        ),
    ]
