#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-12-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0020_auto_20191202_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OCRWorker',
            new_name='WorkerConfig',
        ),
    ]
