#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-12-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0021_auto_20191207_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inouthistory',
            old_name='back_camera',
            new_name='ocr_camera',
        ),
    ]
