#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-12-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0025_auto_20191207_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerconfig',
            name='offline_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(default='rtsp://admin:Abc12345@192.168.1.100:554', max_length=2083, unique=True),
        ),
    ]
