#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-12-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0026_auto_20191220_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerconfig',
            name='offline_video',
        ),
        migrations.AddField(
            model_name='camera',
            name='offline_video',
            field=models.BooleanField(default=False),
        ),
    ]
