#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2019-12-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0028_auto_20191228_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inouthistory',
            name='inout',
            field=models.IntegerField(choices=[(0, 'Unknown'), (-1, 'In'), (1, 'Out')], default=0),
        ),
    ]
