#  Copyright (C) AI Power - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by AI Power, January 2020

# Generated by Django 2.2.6 on 2020-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0029_auto_20191228_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='inouthistory',
            name='container_height',
            field=models.CharField(choices=[('-', 'Unknown'), ('0', '8 feet'), ('2', '8 feet 6 inches'), ('5', '9 feet 6 inches')], default='-', max_length=18),
        ),
        migrations.AddField(
            model_name='inouthistory',
            name='container_length',
            field=models.CharField(choices=[('-', 'Unknown'), ('2', '20 feet'), ('4', '40 feet'), ('L', '45 feet'), ('M', '48 feet')], default='-', max_length=18),
        ),
        migrations.AddField(
            model_name='inouthistory',
            name='container_str',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='inouthistory',
            name='container_code',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='inouthistory',
            name='inout',
            field=models.IntegerField(choices=[(-1, 'In'), (0, 'Unknown'), (1, 'Out')], default=0),
        ),
    ]
