# Generated by Django 3.0.7 on 2020-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0030_auto_20200301_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(default='rtsp://custom_admin:Abc12345@192.168.1.100:554', max_length=2083, unique=True),
        ),
    ]
